// components/InfoMessage.tsx
import type {ReactElement} from 'react';

function	InfoMessage({status}: {status: string}): ReactElement {
	if (status === 'use_production' || status === 'endorsed') {
		return (
			<div className={'my-4 max-w-5xl bg-yearn-blue p-4 font-mono text-sm font-normal text-white'}>
				{'🚀 '}<strong>{'YEARN WEBSITE'}</strong> {"this vault is in Yearn Finance website. You don't need to move your funds."}
			</div>
		);
	}
	if (status === 'withdraw') {
		return (
			<div className={'my-4 max-w-5xl bg-red-900 p-4 font-mono text-sm font-normal text-white'}>
				{'🛑 '}<strong>{'WITHDRAW YOUR FUNDS'}</strong> {'this experiment is disabled and it will not generate more yield. Please remove your funds.'}
			</div>
		);
	}
	return (
		<div className={'my-4 max-w-5xl bg-yellow-900 p-4 font-mono text-sm font-normal text-[#485570]'}>
			{'⚠️ '}<strong>{'WARNING'}</strong> {"this experiments are experimental. It's extremely risky and will probably be discarded when the test is over. Proceed with extreme caution."}
		</div>
	);
}

export default InfoMessage;

// src/components/InfoMessage.vue
<template lang="pug">
	div(class="info-message")
		span(v-if="status === 'withdraw'")
			| 🛑 <strong>WITHDRAW YOUR FUNDS</strong> this experiment is disabled and it will not generate more yield.
			| Please remove your funds.
		span(v-else-if="status === 'endorsed'")
			| 🚀 <strong>YEARN WEBSITE</strong> this vault is in Yearn Finance website. You don't need to move your funds.
		span(v-else)
			| ⚠️ <strong>WARNING</strong> this experiment is experimental.
			| It's extremely risky and will probably be discarded when the test is over.
			| Proceed with extreme caution.
</template>

<script>

export default {
	name: 'InfoMessage',
	props: ['status'],
	data() {
		return {
			message_type: '',
		};
	},

	computed: {},
	created() {
		switch(this.status) {
		case 'withdraw':
			this.message_type = 'is-danger';
			break;
		case 'endorsed':
			this.message_type = 'is-info';
			break;
		default:
			this.message_type = '';
		}
	},

};

</script>
<style>
.tag {
	margin-left: 1em;
}
a strong {
	color: blue !important;
}

a strong:hover {
	color: black !important;
}
</style>
